### PR TITLE
Nikolai/fix/crash on gallery image add

### PR DESCRIPTION
**Pull request by lizard-52**
Fix a bug I made

### CODE REVIEW

**Review by Yunyang-Lu — APPROVED** [review]

**Comment by lizard-52** [comment]
Thank you @Yunyang-Lu for help finding and diagnosing this one!

**Review by waridh — COMMENTED** [review]
The code looks good, but I cannot confirm that this works on my end since my emulator has an empty gallery.

**Comment by JoshuaShaw-13** [comment]
When I run this it will not open up the gallery on my phone. To be more specific, when I press "Choose from Gallery" a loading screen pops up for a fraction of a second then goes away, leaving me on the pictures tab in adding an item. This is after I give permission to access photos, so it is not that.

When I ran the code from the serial number description lookup PR, adding a photo from gallery did not cause a crash. I still get a crash from main when adding via gallery though.

**Comment by lizard-52** [comment]
Hang on, there a fix for that on main. I need to update the branch first.

**Comment by JoshuaShaw-13** [comment]
I am still getting the same issue, is anyone else getting the issue? If it has been fixed maybe it is on my end.

**Comment by lizard-52** [comment]
Try invalidating your android studio cache. If that doesn't work can you send me the error message?

**Review by echeng-git — APPROVED** [review]
Works on my phone, this is good to merge.

**Pull request merged**
