### PR TITLE
Bach/feature/connect fragment to host activity

### PR DESCRIPTION
**Pull request by waridh**
Right now the list view is able to launch the fragment, and the fragment can close itself. There isn't any transfer of data yet, but it should soon be implemented.

### CODE REVIEW

**Review by echeng-git — COMMENTED** [review]
Looks fine, but as Nikolai mentioned, you will need to add a ``getInstance()`` method for QueryFragment.

**Comment by waridh** [comment]
so global context has actually been removed from this pr for now. QueryFragment will not have an instance of globalContext until it is needed.

**Comment by lizard-52** [comment]
Just add the two lines of code for global context. Who ever works on it next will need it anyways.

**Comment by waridh** [comment]
Hi, are we going to move forward with this branch? Or do we want to hold it in pr?

**Review by lizard-52 — APPROVED** [review]
Yes

**Pull request merged**
