### PR TITLE
Jfshaw1/feature/app icon

### PR DESCRIPTION
**Pull request by JoshuaShaw-13**
Adds custom app icon. Can be seen on launch of app as well

### CODE REVIEW

**Review by lizard-52 — COMMENTED** [review]
What are all the .webp files?

**Comment by JoshuaShaw-13** [comment]
> What are all the .webp files?

Image files for the app icon

**Review by waridh — APPROVED** [review]
How hard was this to implement? For future reference, would it be hard to change?

**Comment by JoshuaShaw-13** [comment]
> How hard was this to implement? For future reference, would it be hard to change?

Will not be hard to change at all. It was weird to get it to work, but will be simple to do again

**Review by lizard-52 — APPROVED** [review]
yes

**Pull request merged**
