### PR TITLE
Bach/feature/filter date

### PR DESCRIPTION
**Pull request by waridh**
done adding the filter date feature. There is room for refactoring. I would like to do those refactors myself after tags has been implemented.

### CODE REVIEW

**Review by bpaul2 — CHANGES_REQUESTED** [review]
Why do we need Quadruple. This is actually redundant

**Comment by waridh** [comment]
> Why do we need Quadruple. This is actually redundant

Should I nest pairs twice, or use an arraylist? Like, I just need to store four things in order, like a tuple, but java doesn't have a nice tuple implementation.

**Comment by waridh** [comment]
You tell me how I contain three different type in the same data structure without making a generic container like these.

**Comment by waridh** [comment]
These aren't issues, I made these structs because we needed it. Would you rather I inline the struct and make four setters for each of them?

**Comment by waridh** [comment]
Typecasts out of an object array? Object arraylist? These should not be solved via inheritance. They needed generics.

**Comment by lizard-52** [comment]
I'm making a PR to remove Pair, removing quad should be similar.

**Comment by waridh** [comment]
We need to talk. Are you coming to class?

**Comment by lizard-52** [comment]
Making another PR on a different branch. The merging was super confusing and I had to resort to copy-paste.

**Pull request closed without merging**
