### PR TITLE
UI Add/Edit Changes

### PR DESCRIPTION
**Pull request by bpaul2**
This implements tabs partitioning for the EditFragment. Next part will include the DetailsFragment.

### CODE REVIEW

**Review by lizard-52 — APPROVED** [review]
Code runs ok, and looks ok too

**Comment by bpaul2** [comment]
This now includes support for the details section

**Comment by lizard-52** [comment]
Hitting the back button from the gallery causes a crash

**Comment by lizard-52** [comment]
Working on a fix now

**Comment by waridh** [comment]
Another testing item that I just did that may or may not be an issue? When I try to add a tag, and press the color? button, and nothing shows up. If I press save, it will crash the app.

**Review by waridh — APPROVED** [review]
UI LGTM

**Pull request merged**
