### PR TITLE
Bach/feature/item list

### PR DESCRIPTION
**Pull request by waridh**
# What was done

- Implemented the skeleton for:
    - ItemList
    - ItemListAdapter
    - IAdapter (Interface for lists that can be adapted.

### CODE REVIEW

**Comment by lizard-52** [comment]
I'm all for documenting our code, but I think detailed comments for every getter and setter is a bit overkill

**Review by lizard-52 — APPROVED** [review]
Looks well thought out and fine to merge.

**Review by bpaul2 — APPROVED** [review]
Looks good

**Review by JoshuaShaw-13 — APPROVED** [review]
Looks good to merge to me

**Pull request merged**
